" Don't pretend to be vi
set nocompatible

" Use my terminal color vim colorscheme
colorscheme thermo


" Allow backspacing over everything in insert mode.
set backspace=indent,eol,start

set history=200		" keep 200 lines of command line history
set wildmenu		" display completion matches in a status line
set showcmd			" Show in-progress commands
set ruler			" Show cursor location
set nowrap          " Don't wrap text

" Set shift width to 4 spaces.
set shiftwidth=4
" Set tab width to 4 columns.
set tabstop=4
" Use tabs, not spaces
set expandtab

" Numbers on side
set number
" Relative numbers
set relativenumber
" Highlight cursor line underneath the cursor horizontally.
set cursorline



" Include all subdirectories in file search paths
set path+=**

let mapleader = ' '

" Filetype syntax
syntax enable

" Filetype detection, as well as using filetype plugin and indent files
filetype plugin indent on

" Always show status line
set laststatus=2

" Column at 80 characters
set colorcolumn=80


" ignore case in search, unless a capital char is entered
set ignorecase
set smartcase
" highlight search results during searching and after query
set incsearch
set hlsearch

" Scroll buffer when moving cursor within 5 lines of edge of visible text
" as well as within 10 columns of the edge of visible text
set scrolloff=5
set sidescrolloff=10

" show menu for completions, but don't select any completion, even if only one
" option is available
set completeopt=menu,menuone,noselect

" Mouse support
if has('mouse')
	set mouse=a
	set ttymouse=sgr
endif

" key mappings
" leader-based splits
nmap <leader>sv :vsplit<CR>
nmap <leader>sh :split<CR>

" Visual mode indenting "keep-active"
vmap < <gv
vmap > >gv

" Opening Netrw and find command
nmap <leader>e :Explore<CR>
nmap <leader>ff :find 


