#!/bin/sh
# Programs to run on startup


# Kill current waybar instances
pkill waybar

# Start tray applets if they aren't already running
[ -n "$(pgrep gammastep)" ] || riverctl spawn gammastep-indicator
[ -n "$(pgrep nm-applet)" ] || riverctl spawn nm-applet
[ -n "$(pgrep blueman-applet)" ] || riverctl spawn blueman-applet
[ -n "$(pgrep udiskie)" ] || riverctl spawn 'udiskie --no-automount --tray'

riverctl spawn 'waybar -c ~/.config/river/waybar/config'

# Playerctl daemon - handles which media player receives media commands
riverctl spawn 'playerctld daemon'

# Swaybg for backgrounds
[ -n "$(pgrep swaybg)" ] || riverctl spawn 'swaybg -i ~/backgrounds/zen2ccd.png -m fill'

# Swayidle for handling idling and locking
[ -n "$(pgrep swayidle)" ] || riverctl spawn 'swayidle -w timeout 600 gtklock \
				lock gtklock \
				before-sleep gtklock'

[ -n "$(pgrep sleep)" ] || riverctl spawn "systemd-inhibit --what=handle-power-key sleep infinity"

# Authentication agennt
[ -n "$(pgrep polkit-mate-authentication-agent-1)" ] || riverctl spawn "/usr/lib/mate-polkit/polkit-mate-authentication-agent-1"

# Spawn mako for notifications unless it's already running (unlikely)
[ -n "$(pgrep mako)" ] || riverctl spawn mako

# Open autostart programs
# Also set their locations
riverctl rule-add -app-id "org.mozilla.Thunderbird" tags $((1 << 4))
riverctl rule-add -app-id "spotify" tags $((1 << 3))
riverctl rule-add -app-id "steam" tags $((1 << 2))

[ -n "$(pgrep steam)" ] || riverctl spawn 'steam -silent'
[ -n "$(pgrep spotify)" ] || riverctl spawn "flatpak run com.spotify.Client"
[ -n "$(pgrep thunderbird)" ] || riverctl spawn "flatpak run org.mozilla.Thunderbird"

riverctl set-focused-tags 2
[ -n "$(pgrep firefox)" ] || riverctl spawn firefox
