#!/bin/sh
# Programs to run on startup


# Kill current waybar instances
pkill waybar

# Start tray applets if they aren't already running
[ -n "$(pgrep gammastep)" ] || riverctl spawn gammastep-indicator
[ -n "$(pgrep nm-applet)" ] || riverctl spawn nm-applet
[ -n "$(pgrep blueman-applet)" ] || riverctl spawn blueman-applet
[ -n "$(pgrep udiskie)" ] || riverctl spawn 'udiskie --no-automount --tray'

riverctl spawn 'waybar -c ~/.config/river/waybar/config'

# Swaybg for backgrounds
riverctl spawn 'swaybg -i ~/backgrounds/zen2ccd.png -m fill'

# Swayidle for handling idling and locking
riverctl spawn 'swayidle -w timeout 600 gtklock \
				lock gtklock \
				before-sleep gtklock'


# Spawn mako for notifications unless it's already running (unlikely)
[ -n "$(pgrep mako)" ] || riverctl spawn mako

# Open autostart programs
# Also set their locations

[ -n "$(pgrep steam)" ] || riverctl spawn 'steam -silent'

riverctl rule-add -app-id "org.mozilla.Thunderbird" tags 000010000
riverctl rule-add -app-id "spotify" tags 000001000

[ -n "$(pgrep spotify)" ] || riverctl spawn "flatpak run com.spotify.Client"
[ -n "$(pgrep thunderbird)" ] || riverctl spawn "flatpak run org.mozilla.Thunderbird"
